### ISSUE TITLE
Error message when attempting to Extract Screen Definition(s) in v1.13.2 with Maximo 7.6.1.2

### ISSUE THREAD

**Issue by yashraf82** [sharptree/vscode-autoscript-deploy#10]
When attempting to either Extract All Screens or Extract a single Screen Definition in Maximo Development Tools v1.13.2 connected to Maximo 7.6.1.2, the following error is received:
[ERROR] [MXServer] [CID-MXOSLC-34307] ReferenceError: "SAXBuilder" is not defined

Following that, the timeout error is seen:
"timeout of 30000 ms exceeded"

It was initially successful in fetching 14 XML definitions of ~300 XML definition, but has failed since. I have tried numerous different screen definitions, but none appear to be working unfortunately. However, Inspection Forms and Autoscripts are working as expected both in extracting and deploying.

**Comment by jvenhuizen** [comment]
It could be that extracting all screens is just taking a long time.  The timeout value can be changed in the settings, the default is 30 seconds / 30,000 milliseconds.

<img width="549" alt="image" src="https://github.com/sharptree/vscode-autoscript-deploy/assets/68662794/1e29de19-a09e-461e-bcdd-176dc05a921d">

**Comment by hcblassingame** [comment]
I've got the same issue in 7.6.1.2.  I tried increasing the timeout, but still have the same issue as yashraf82. 

I found an older version of the SHARPTREE.AUTOSCRIPT.SCREENS script on one of our dev environments (version of the script shows as 1.15, whereas the latest version shows as 1.28.

I brought the older 1.15 version into my environment and was able to export all screen definitions.

I wonder if it's to do with the block starting around line 26 that brings in the org.jdom2.input.SAXBuilder or org.jdom.input.SAXBuilder, and whether that class is present in the version of Java 7.6.1.2 is using? I don't see that class in the older version of the script.

**Comment by jvenhuizen** [comment]
Reviewing the script, if an error occurs when attempting to load the SAXBuilder we check if the error is a classnotfound error, which occurs with the move to JDOM2 in newer environments. But, if the error was not related to being a classnotfound error it would not throw the error and the underlying issue would be lost.  I have updated this to now throw the error if it is not a classnotfound error so at least we can capture what is actually going on.
