### ISSUE TITLE
Couldn't connect to Maximo during first time. Get error 'Content-Type header is not application/json'

### ISSUE THREAD

**Issue by eliyx** [sharptree/vscode-autoscript-deploy#11]
Hi, I'm trying to connect this to Maximo the first time, but the Command Pallete does not have the option to execute "Deploy Automation Script". Only "Deploy to Maximo" is there.
![image](https://github.com/sharptree/vscode-autoscript-deploy/assets/16609992/d59e1de1-f278-4b1d-84ce-91e3ce36d24a)

I'm on version 1.13.2

Simply getting an error: 'Content-Type header is not application/json'
![image](https://github.com/sharptree/vscode-autoscript-deploy/assets/16609992/28654a2d-e206-45c5-8af7-3f4f7c4431e5)

Am i missing something? thanks

**Comment by jvenhuizen** [comment]
The error indicates that the response from the server isn't JSON. I have seen this where there is SAML or another redirect in place.  If you are using SAML then you will need to use the API Key authentication since SAML is not supported by the extension.

**Comment by jvenhuizen** [comment]
Closing for lack of response.
