### ISSUE TITLE
scriptConfig MaxVars Deploy Fails

### ISSUE THREAD

**Issue by jaredschrag** [sharptree/vscode-autoscript-deploy#17]
When I try to deploy an Automation Script that includes a `maxvars` property, there appears to be a bug. With this `scriptConfig` excerpt:
```
scriptConfig = """{
   ...
   "maxvars": [
      {
         "varName": "MYVARNAME",
         "description": "My description goes here",
         "varType": "SYSTEM",
         "varValue": "VALUE1"
      }
   ]
}"""
```

I am seeing this error:
![2024-07-29_16-50-00](https://github.com/user-attachments/assets/b14081bd-b451-4ed9-adde-767a074841b8)

I suspect strongly that the issue is that the SHARPTREE.AUTOSCRIPT.DEPLOY Automation Script is looking for the MAXVARS.VARVALUE value to be found in the `maxvar.varvalue` property when it should be using camelCase for the property names. Therefore, it should probably try to retrieve the VARVALAUE from the `maxvar.varValue` property.

**Comment by jaredschrag** [comment]
I also suspect there may be a mixup between "varType" and "maxType" - not sure, still testing it.

**Comment by jaredschrag** [comment]
I found that one work-around is to specify the varType and the varValue twice as follows:
```
scriptConfig = """{
   ...
   "maxvars": [
      {
         "varName": "MYVARNAME",
         "description": "My description goes here",
         "maxType": "SYSTEM",
         "varType": "SYSTEM",
         "varValue": "VALUE1",
         "varvalue": "VALUE1"
      }
   ]
}"""
```

**Comment by jvenhuizen** [comment]
First off, I am sorry I haven't responded sooner.  For some reason GitHub isn't notifying me when new issues are submitted.  Second, I will look into this and get a fix out.

That error indicates that there is a problem where there is a null value and it can't figure out which overload to use.

**Comment by jvenhuizen** [comment]
You were correct that there was a mixup between varType and maxType.

**Comment by jvenhuizen** [comment]
This has been fixed in 1.15.8.  I have also updated our repo settings so I will get notified when you submit future issues.

**Comment by jaredschrag** [comment]
@jvenhuizen  I think there still a slight bug, please review the code block below. I think the `if` statement should probably test for `undefined` in the `maxvar.varValue` property (instead of `maxvar.varvalue`).

https://github.com/sharptree/vscode-autoscript-deploy/blob/0fd2e57af19c63fadbf34b0ee85222c512083fa6/resources/sharptree.autoscript.deploy.js#L836-L840

**Comment by jvenhuizen** [comment]
🤦 well that is embarrassing.  I have applied the fix and it is publishing now.

**Comment by jaredschrag** [comment]
This fix appears to be working without any issue! Thanks again, Jason!

**Comment by jvenhuizen** [comment]
Fixed per originator.
