### ISSUE TITLE
Predeploy maxObjects attribute persistent value of false not properly set in maxattributecfg

### ISSUE THREAD

**Issue by jmarkeaton** [sharptree/vscode-autoscript-deploy#19]
Within the predeploy JSON, I am rocking along, but have found that the persistent value of "false" is not properly setting the attribute persistent value.

Attribute configuration in question:
    {"attribute": "EMXSPECACTIONS",
	    "description":"Spec Actions",
	    "type":"YORN",
	    "length": 1,
	    "title": "Spec Actions",
	    "persistent" : "false"
    }

**Comment by jmarkeaton** [comment]
Found the issue; the code is looking for presistent instead of persistent (sp)

**Comment by jvenhuizen** [comment]
You want to use:

`{"attribute": "EMXSPECACTIONS",
"description":"Spec Actions",
"type":"YORN",
"length": 1,
"title": "Spec Actions",
"persistent" : false
}`

with false not in quotes as the "false" is a string and actually evaluates to true with JavaScript's truthiness.

**Comment by jvenhuizen** [comment]
Fixed based on feedback.
