### ISSUE TITLE
Missing "interface" Property (Allow Invoking Script Functions) When AutoScript is Added

### ISSUE THREAD

**Issue by jaredschrag** [sharptree/vscode-autoscript-deploy#20]
It appears that the "Allow Invoking Script Functions" option when a new Automation Script is created in Maximo is not really supported by the the Deploy Script functionality. It seems this would be easy to implement, in the `SHARPTREE.AUTOSCRIPT.DEPLOY` script, in the `deployScript` function, when a the automation script does not yet exist, it will add a new one to the mboset and it initially sets some of the attributes, such as `AUTOSCRIPT`, `SCRIPTLANGUAGE`, and `ACTIVE` - it seems like another `scriptConfig` property called `interface` (or `allowInvokingScriptFunctions`), could be used to set the `INTERFACE` attribute during the Automation Script creation.

**Comment by jvenhuizen** [comment]
I'll look into it.  Again, apologies for the late response.

**Comment by jvenhuizen** [comment]
This has been fixed in 1.15.8. Once you have a chance to confirm and let me know it is fixed I will close this ticket.

**Comment by jaredschrag** [comment]
@jvenhuizen This fix seems to be working! I will note; however, it allows something that cannot be done in the front-end - it allows updating that INTERFACE attribute on an existing Script (in the front-end it only allows the setting of this attirbute on a new, unsaved Script). However, I don't really see an issue with allowing the update to occur on an existing Script. Thanks!!

**Comment by jvenhuizen** [comment]
There are actually quite a few places where we allow updates that the front end doesn't because the idea is that whatever your are deploying is the source of truth.  So when we deploy we are deleting and recreating the script and all its attributes.

**Comment by jvenhuizen** [comment]
Closing based on originator's configuration.
