### ISSUE TITLE
Exporting BIRT reports records incorrect "multilookup" YORN into reports.xml 

### ISSUE THREAD

**Issue by G3iMacMan** [sharptree/vscode-autoscript-deploy#24]
When exporting BIRT reports, the value for the multilookup field is recorded in the reports.xml document as "true" or "false". 
When this is deployed back into Maximo, regardless of the value, the field is set to false.

Manually changing the values in reports.xml to 1 or 0, matching all other YORN values, the deployment correct sets the  value for multilookup.

**Comment by jvenhuizen** [comment]
Thank you for the feedback, we will test and release a fix shortly.

**Comment by jvenhuizen** [comment]
This has been fixed in 1.16.0
