### ISSUE TITLE
how to connect to IP with Port.

### ISSUE THREAD

**Issue by arkprabha** [sharptree/vscode-autoscript-deploy#3]
Thanks for the wonderful tool which makes life lot easier 

I have a system which is not webserver enabled. which means there is no URL. only IP for example 10.41.**.**:9080/maximo how can we configure this in sharptree?
thanks

**Comment by jvenhuizen** [comment]
You can use the IP address instead of the host name. 

![image](https://user-images.githubusercontent.com/68662794/208972313-f9263967-294c-4234-83c5-457d0b8bd926.png)
