### ISSUE TITLE
MAS 8 Install Issue

### ISSUE THREAD

**Issue by John-PEL** [sharptree/vscode-autoscript-deploy#4]
I've come across an issue when trying to use the the tools with MAS Manage.

I'm using API key to authenticate and version IBM Maximo Manage 8.4.5 Build 20230104-0903 DB Build V8400-03.

The install process successfully manages to create SHARPTREE.AUTOSCRIPT.INSTALL but then (eventually) returns a timeout error. If I then login to Manage it seems there is a long running process tying-up Maximo causing endless spinning circles. I can't see anything obvious in the logs, could the install script be stuck in a circular loop?

**Comment by jvenhuizen** [comment]
I apologize for not responding sooner, but for some reason Git hub did not notify me of your submission and I only now noticed it.

I have not seen this in any of our development environments, but it is theoretically possible that there is a bug that is causing the script to fail.  The installation script does log under the automation script logger so if you set it to debug you should see if there is repeated output. 

Unfortunately, there has been a lot of churn with MAS lately and a lot of different versions so it is hard to match and reproduce your exact scenario.  Have you updated to the latest 8.6 release and are you able to reproduce the error?  Any additional details you can provide would be helpful and I would like to provide a fix if possible.

Jason

**Comment by John-PEL** [comment]
@jvenhuizen, thanks for coming back to me. 

I decided to upgrade the MAS environment (to V8700-96) but now I get an error saying that version isn't supported - possibly due to the new auth change from IBM? Is support for this version on the roadmap anytime soon?

**Comment by jvenhuizen** [comment]
I have updated with Manage 8.7 support.  I had not had a chance to validate it against a MAS 8.11 environment.  Thanks for the nudge.
