### ISSUE TITLE
Manage 8.6.3 :: While extracting screens getting error "java.lang.ClassNotFoundException: org.jdom.Element"

### ISSUE THREAD

**Issue by spukkala** [sharptree/vscode-autoscript-deploy#6]
I am using the latest release of the code add-on on MAC. I am able to download and deploy Automation Scripts but getting jdom error while extracting the presentations file. 

Regards.
Suri

**Comment by jvenhuizen** [comment]
Confirmed the bug and it is specific to MAS 8.6. I will work to get a fix out shortly.

**Comment by jvenhuizen** [comment]
MAS 8.6 dropped the legacy JDOM library, which was causing the error.  Updated to use JDOM2 and released 1.13.2 with the fix.
