### ISSUE TITLE
Deploy Inspection Error on DocType of Inspection

### ISSUE THREAD

**Issue by atess-pnnl** [sharptree/vscode-autoscript-deploy#7]
In sharptree.autoscript.form.js on line 632 var applications = ["INSPECTOR", "INSPECTORSUP", "INSPECTION"]; "INSPECTION" was added in 1.13. in a Maximo 7.6.1.2  and a separate 7.6.1.3 this is causing an error. Error is BMXAA4191E - The value INSPECTION is not valid for Application. Specify a valid value for Application. 
Removing Inspection from the automation script results in a successful deploy of the inspection form.

**Comment by jvenhuizen** [comment]
A fix for this has been published as version 1.13.1.
