### ISSUE TITLE
Automated deployment from Git/Github repo

### ISSUE THREAD

**Issue by scerdal** [sharptree/vscode-autoscript-deploy#8]
Hello, firstly I wanted to say I really appreciate this extension and wanted to thank you for your efforts. The documentation states that 
> The provided SHARPTREE.AUTOSCRIPT.DEPLOY automation script provides support for build pipelines and automated deployment of automation scripts from a Git repository.

but does not provide details as to how to do that. Could you explain how we would be able to automate deployment from a Git repository? I would love to deploy to Maximo using Github Actions, but am not sure if this is possible as of now.

**Comment by jvenhuizen** [comment]
I have had it on my list to write up a blog post on this, I just have not had the time to do it. Internally, we use Azure DevOps and I can share what we do there, something similar should be possible on GitHub.

If you want to do a quick Teams meet that may be the easiest thing (for me at least) and I can show what we have.  You can reach me at jason@sharptree.io

Thanks for your kind words and I am happy to hear that it helps you out.

**Comment by scerdal** [comment]
Jason, thank you for your kind response and your willingness to meet online. Since my comment, I actually did dive into the code a bit and was able to construct a sample POST request to call the deploy script and get it to create my script in Maximo. I believe I can take it from here to build a GitHub actions workflow that makes these POST requests for each script in my GitHub repository. Let me know if this is along the lines of what you were going to suggest.

**Comment by jvenhuizen** [comment]
Oh, you don't need to do it manually there is a command line version of the VS Code tools here:

https://www.npmjs.com/package/maximo-dev-tools

You just need to install Node JS 16+ and then install the utility and call the command.  There is documentation on the NPM page for the command line parameters.  Let me know if you have any questions.

**Comment by scerdal** [comment]
That's even better :)

**Comment by jvenhuizen** [comment]
Closing.
