### ISSUE TITLE
Deploy Objects using maximo-dev-tools tool

### ISSUE THREAD

**Issue by scerdal** [sharptree/vscode-autoscript-deploy#9]
Hello again,

Is it possible to deploy objects like cron tasks and properties to Maximo using the maximo-dev-tools CLI tool? Thank you.

**Comment by jvenhuizen** [comment]
As of version 1.13 we support including a number of different objects including CronTasks.  Documentation for this feature is under the On Deploy Properties header.  Just include a file with the same name as your script with a .json extension and the tools will automatically deploy the described objects.
